### ISSUE TITLE
How can we style zoomLens??

### ISSUE THREAD

**Issue by pkumar01** [malaman/js-image-zoom#13] opened 2018-09-28 11:09 UTC
Existing implementation only allows to change opacity and background color of zoom lens but i want to manage the width and height too, is there any workaround to handle zoomlens width height too??

**Comment by malaman** [comment] 2018-10-08 08:28
Duplicate of https://github.com/malaman/react-image-zoom/issues/9

**Closed as completed by malaman** 2018-10-08 08:28 UTC
